/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pinet_cdemounlink_c_NDKCConst */

#ifndef _Included_com_pinet_cdemounlink_c_NDKCConst
#define _Included_com_pinet_cdemounlink_c_NDKCConst
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_pinet_cdemounlink_c_NDKCConst
 * Method:    executeCConst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKCConst_executeCConst
  (JNIEnv *, jobject);




#ifdef __cplusplus
}
#endif
#endif
