/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pinet_cdemounlink_c_NDKOverLoad */

#ifndef _Included_com_pinet_cdemounlink_c_NDKOverLoad
#define _Included_com_pinet_cdemounlink_c_NDKOverLoad
#ifdef __cplusplus
extern "C" {




JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKOverLoad_executeConst
        (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKOverLoad_executeCppPointer
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKOverLoad_executeCppConstsPointer
        (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKOverLoad_executeCppInlineFun
        (JNIEnv *, jobject);



JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKOverLoad_executeCppFunParam
        (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKOverLoad_executeFunClass
        (JNIEnv *, jobject);

#endif
/*
 * Class:     com_pinet_cdemounlink_c_NDKOverLoad
 * Method:    executeConst
 * Signature: ()V
 */


#ifdef __cplusplus
}
#endif
#endif
