/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pinet_cdemounlink_c_NDKCPP */

#ifndef _Included_com_pinet_cdemounlink_c_NDKCPP
#define _Included_com_pinet_cdemounlink_c_NDKCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pinet_cdemounlink_c_NDKCPP
 * Method:    callCppConstruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKCPP_callCppConstruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
