/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pinet_cdemounlink_c_NDKCppInterface */

#ifndef _Included_com_pinet_cdemounlink_c_NDKCppInterface
#define _Included_com_pinet_cdemounlink_c_NDKCppInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pinet_cdemounlink_c_NDKCppInterface
 * Method:    excuteCppCustruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKCppInterface_excuteCppCustruct
  (JNIEnv *, jobject);

/*
 * Class:     com_pinet_cdemounlink_c_NDKCppInterface
 * Method:    executeCppDesctruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKCppInterface_executeCppDesctruct
  (JNIEnv *, jobject);



JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKCppInterface_executeCppCopyFun
        (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKCppInterface_executeCppScenes
        (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_pinet_cdemounlink_c_NDKCppInterface_executeCppCopy
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
